backend:
  name: github
  branch: main
  repo: soap73/soap-editing  # Remplacer "owner" par ton username GitHub
  base_url: https://soap-editing-oauth.anthony-vuillerot.workers.dev  # URL de ton Worker Cloudflare
  auth_endpoint: /oauth/callback

media_folder: "public/projects"
public_folder: "/projects"

site_url: "https://soap-editing.pages.dev"
display_url: "https://soap-editing.pages.dev"
logo_url: "https://soap-editing.pages.dev/favicon.svg"
locale: "fr"

collections:
  - name: "projects"
    label: "Projets"
    label_singular: "Projet"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    editor:
      preview: false
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "URL de la vidéo", name: "videoUrl", widget: "string" }
      - label: "Catégorie"
        name: "category"
        widget: "select"
        options:
          - { label: "YouTube", value: "youtube" }
          - { label: "Court-Métrage", value: "court-metrage" }
          - { label: "Réseaux Sociaux", value: "reseaux-sociaux" }
        default: "youtube"
      - { label: "Miniature", name: "thumbnail", widget: "image", required: false }
